#!/usr/bin/env bash
#Display information about the subdomain
domain="$1"

# Define subdomains
subdomains=("www" "lb-01" "web-01" "web-02")

# Function to get DNS record type and destination
get_record_info() {
    local sub="$1"
    local record_type=$(dig +noall +answer "$sub.$domain" | awk '{print $4}')
    local destination=$(dig +short "$sub.$domain" | awk '{print $1}')
    echo "The subdomain $sub is a $record_type record and points to $destination"
}

# Display information based on arguments
if [ $# -eq 1 ]; then
    # Display info for all subdomains
    for sub in "${subdomains[@]}"; do
        get_record_info "$sub"
    done
else
    # Display info for specified subdomain
    get_record_info "$2"
fi
