#!/usr/bin/env bash

sudo apt update
sudo apt-get install -y certbot haproxy

DOMAIN='life-blog.tech'

sudo certbot certonly --standalone --preferred-challenges http --http-01-port 80 -d www.life-blog.tech

ls /etc/letsencrypt/live/www.life-blog.tech/

# Define paths to the certificate and key
CERT_PATH="/etc/letsencrypt/live/www.life-blog.tech/fullchain.pem"
KEY_PATH="/etc/letsencrypt/live/www.life-blog.tech/privkey.pem"
COMBINED_PATH="/etc/haproxy/certs/$DOMAIN.pem"
DH_PARAM_PATH="/etc/haproxy/dhparam.pem"

# Ensure the certificate and key files exist
if [ ! -f "$CERT_PATH" ] || [ ! -f "$KEY_PATH" ]; then
    echo "Error: Certificate or key file not found."
    exit 1
fi


# Combine the certificate and private key into one file
sudo cat "$CERT_PATH" "$KEY_PATH" > "$COMBINED_PATH


# Generate DH parameters
sudo openssl dhparam -out "$DH_PARAM_PATH" 2048

# Append DH parameters to the combined certificate file
sudo cat "$DH_PARAM_PATH" >> "$COMBINED_PATH"

sudo chmod -R go-rwx /etc/haproxy/certs

# configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOL
defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        option  forwardfor
        timeout connect 5000
        timeout client  50000
        timeout server  50000
        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http

frontend httpandhttps
        bind *:80
        bind *:443 ssl crt /etc/haproxy/certs/life-blog.tech.pem
        http-request set-header X_Forwarded-Proto https if { ssl_fc }
        default_backend web-backend

backend web-backend
        balance roundrobin
        server 428584-web-01 35.153.51.52:80 check
        server 428584-web-02 34.229.189.140:80 check
EOL

sudo systemctl restart haproxy
