#!/usr/bin/env bash
# install nginx and run sample

echo "Installing Nginx"
sudo apt-get -y update
sudo apt-get install -y nginx

# "configure the HTTP port"
sudo ufw allow 'Nginx HTTP'

# "Grant ownership permission"
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# create a new index
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# start nginx
sudo service nginx start
