#!/usr/bin/env bash
# Script configures Ubuntu server with
# localhost resolving to 127.0.0.2
# facebook.com resolving to 8.8.8.8
sudo cp /etc/hosts /etc/hosts.new

# Edit hosts file to configure the requirements
sudo bash -c 'echo "127.0.0.2 localhost" >> /etc/hosts'
sudo bash -c 'echo "8.8.8.8 facebook.com" >> /etc/host'
