#!/usr/bin/env bash
# Script that starts nginx as nginx user
chmod 777 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chown nginx:nginx /etc/nginx/nginx.conf
pkill -9 apache
su nginx -c "service nginx restart"
